### ISSUE TITLE
Rule: /cdn-cgi/pe/bag2?r[]=http$xmlhttprequest

### ISSUE THREAD

**Issue by collinbarrett** [IDKwhattoputhere/uBlock-Filters-Plus#1]
I recently started using your list, and I noticed that the rule below seems to get triggered on all sites that are served over CloudFlare (I think it's their RocketLoader feature, example site: https://filterlists.com/ ). I know it is marked as an experimental rule, so I just wanted to point that out/inquire as to if that was intentionally targeted towards all CloudFlare sites or toward a a specific tracker that happens to possibly use CloudFlare. This rule could potentially have a negative impact on a lot of sites. Which is fine, if it needs to, just pointing that out.

/cdn-cgi/pe/bag2?r[]=http$xmlhttprequest

Thanks for the great list!

**Comment by IDKwhattoputhere** [comment]
I'm aware of that and I might comment that rule out. This CloudFlare feature is used on some sites (like previously on gamebana.com) to load some advertising scripts. A couple of more specific rules are already in EasyList and EasyPrivacy. Examples:
```
/cdn-cgi/pe/bag2?r[]=*adblade.com
/cdn-cgi/pe/bag2?r[]=*adk2.co
/cdn-cgi/pe/bag2?r[]=*ads.exoclick.com
```
I believe RocketLoader can be used for all scripts so a rule for every advertising/tracking domain would be needed. This was the reason I added the broad rule. I didn't see any breakage on Gamebanana or forums.lanik.us but as I understand it blocking it might make pages load slower since the scripts have to be loaded from their original source. So I'm not sure if it's worth having this filter.

Thanks for the kind words.

**Comment by collinbarrett** [comment]
Hmm, ok, that makes sense. I can try to do a bit of digging too if I have a chance. But, yeah, replacing it to allow RocketLoader to function on non-tracking sites would require verbose, custom rules, I would think.

**Comment by collinbarrett** [comment]
In case anybody wants to temporarily override this rule until it is researched further, I am using this custom filter to successfully do so.

`@@/cdn-cgi/pe/bag2?r[]=http$xmlhttprequest`

**Comment by IDKwhattoputhere** [comment]
Commented it out for now. If more sites start using it for advert/tracking servers I'll add it again.
