### ISSUE TITLE
why does this list block Android Gmail app?

### ISSUE THREAD

**Issue by rcmpayne** [IDKwhattoputhere/uBlock-Filters-Plus#10]
Using pfsense with pfblockerNG and when this rule is enabled, my LG G4 cant access Gmail app. block is mail.google.com. when i disable this rule, Gmail works just fine.

**Comment by IDKwhattoputhere** [comment]
I'm not sure what to do here. I've never used "pfsense" or "pfblockerNG". This filter list is for uBlock Origin which has [a logger](https://github.com/gorhill/uBlock/wiki/The-logger). That way someone can figure out which requests are being blocked and by which rule. Does "pfblockerNG" have such a feature too? If yes then it would be great if you could try to figure out which filter rule causes the issue. Otherwise I don't know how to help.

**Comment by rcmpayne** [comment]
its the first one "! mail.google.com" thats causing the block.

**Comment by IDKwhattoputhere** [comment]
Strange since that one is not a filter. It's a comment (notice the `!`) which should be ignored. Check [uBlock Origins built-in filters](https://github.com/uBlockOrigin/uAssets/blob/master/filters/filters.txt#L1280) or [EasyList](https://easylist-downloads.adblockplus.org/easylist.txt) for examples. If the comment is used as a filter I would consider this a bug in "pfblockerNG". I have no experience with that software though so maybe this is expected behavior.
Maybe replacing the `!` with a `#` helps as a workaround? Can you somehow test if `# mail.google.com` would be ignored?

**Comment by rcmpayne** [comment]
yea hashtag works

**Comment by IDKwhattoputhere** [comment]
Sorry for taking so long. [This](https://github.com/IDKwhattoputhere/uBlock-Filters-Plus/commit/5c62933042c9076e559bbe7b55e000bf7eb5e212) should fix it.
