### ISSUE TITLE
Sick of those video elements..

### ISSUE THREAD

**Issue by xevidencex** [IDKwhattoputhere/uBlock-Filters-Plus#12]
I can't find filters for them,

[NSFW] pornhubcom
https://i.imgur.com/Y8G64du.png

[NSFW] xxxvoguenet
https://i.imgur.com/HZSIQc5.png

**Comment by IDKwhattoputhere** [comment]
I don't see it with updated uBO 1.15.2. Maybe update filter lists.

**Comment by xevidencex** [comment]
what are your subscriptions ?

**Comment by xevidencex** [comment]
Other site examples where it appears:

xhamster banner:
http://www.myvidster.com/video/64074439/Married_Arab_Guy_Fucks_White_Bitch_Gay_Porn_2a_xHamster

xhamster banner:
http://www.pornpapas.com/guadeloupe-salope-gwada-bitch-pute-antillaise-971/

here, you see another close button only:
http://www.foxporns.com/straight-video-1258436.html

xhamster banner:
http://www.pornotrix.net/dildo/

xhamster banner:
http://www.fastmobileporn.net/asian-sport/

**Comment by IDKwhattoputhere** [comment]
Not seeing anything even with default filter lists. Maybe you accidentally disabled cosmetic filtering in the settings of uBlock Origin? Otherwise try creating a backup of your settings and then reset the settings to defaults. This will show you if the settings are at fault. If that doesn't work I don't know either. Maybe report to forums.lanik.us and see if they can reproduce it.
