### ISSUE TITLE
Remove `popunder` filter option where no longer needed

### ISSUE THREAD

**Issue by gorhill** [IDKwhattoputhere/uBlock-Filters-Plus#2]
In your list, many of the filters have the purpose to block `popunder` -- in addition to `popup`.

With [uBO 1.6.4](https://github.com/gorhill/uBlock/releases/tag/1.6.4), for many of these filters it will become unnecessary to use the `popunder` option, as just using `popup` will be sufficient. uBO 1.6.4 will block popunders as well using `popup` filters, as long as the filter is **not** _broad_ (i.e. `|http://$popup`). The `popunder` option can still be used for when existing `popup` filters do not do the job, because of their broadness.

Examples of filter in your list for which the `popunder` option can be removed (once you have confidence most people are updated to 1.6.4):

    ||adplxmd.com^$popunder,popup
    ||adnetworkperformance.com^$popunder,popup
    ||trimpur.com^$popunder,popup
    ||signetter.com^$popunder,popup
    ||oratosaeron.com^$popunder,popup
    [...]

This should help make the maintenance simpler.

**Comment by IDKwhattoputhere** [comment]
https://github.com/IDKwhattoputhere/uBlock-Filters-Plus/commit/7b637e6e7cc26d42f64bd6ca7b2921d63ae8540d

Hope I did that right. If I tested correctly then the `popunder` option is still needed for filters like `/popunder.$popunder,popup`, right?

Thanks a bunch for making this update. It will in fact make maintenance easier especially since many EasyList popup filters are now being used for popunders too.

**Comment by gorhill** [comment]
> If I tested correctly then the `popunder` option is still needed for filters like `/popunder.$popunder,popup`, right?

Yes, the current code define broad as having at least a part of the hostname being matched.

**Comment by IDKwhattoputhere** [comment]
Alright, thanks.

**Comment by IDKwhattoputhere** [comment]
Is it right that this new change includes filters like `|https://$popup,third-party,domain=userscloud.com` as not broad? Because then I would have to remove those since the sites can't be opened in a new tab.
Also seen here: https://forums.lanik.us/viewtopic.php?f=90&t=28977

**Comment by gorhill** [comment]
> Is it right that this new change includes filters like |https://$popup,third-party,domain=userscloud.com as not broad?

Yes, otherwise doing so would bring back issue <https://github.com/gorhill/uBlock/issues/1010>.

Is there an issue? (I can't read German)

**Comment by IDKwhattoputhere** [comment]
The user's problem is that if they open a Streamcloud link in a new tab the original tab will be closed (provided the site wasn't loaded over SSL) because of the filter `|http://$popup,third-party,domain=streamcloud.eu` in EasyList Germany‎ (fixed [here](https://hg.adblockplus.org/easylistgermany/rev/38bfee3486d9)).
Can be easily reproduced by adding the userscloud.com filter from above and opening [this link](http://userscloud.com/).

**Comment by gorhill** [comment]
> Can be easily reproduced by adding the userscloud.com filter from above and opening this link in a new tab.

I could reproduce... there is a bug, somehow I didn't catch this. Mind opening an issue for uBO while I work on a fix?

**Comment by IDKwhattoputhere** [comment]
Will do.

**Comment by gorhill** [comment]
I know why I missed the tiny mistake, the filter above would work if it was crafted similarly to the one in #1010: `|http:$popup,third-party,domain=streamcloud.eu` would work properly, or even `|http:/$popup,third-party,domain=streamcloud.eu`.

**Comment by IDKwhattoputhere** [comment]
That was fast! Thanks a bunch!
