### ISSUE TITLE
uBlock Filters Plus blocks Amazon's customer support live chat

### ISSUE THREAD

**Issue by anonsubmitter** [IDKwhattoputhere/uBlock-Filters-Plus#7]
uBlock Filters Plus' `/popup.$domain=~webopedia.com,document` filter rule incorrectly blocks Amazon's customer support live chat, for example on: https://www.amazon.com/gp/help/chat/popup.html

I thought that this filter rule should work for all Amazon sites, but for some reason it doesn't:
`/popup.$document,domain=~amazon.ca|~amazon.cn|~amazon.co.jp|~amazon.co.uk|~amazon.com|~amazon.com.au|~amazon.com.br|~amazon.com.mx|~amazon.de|~amazon.es|~amazon.fr|~amazon.in|~amazon.it|~amazon.nl|~webopedia.com`

I can't find that exact filter rule that I pasted in the first paragraph - which uBlock Origin claims is responsible for the blocking - in the filterlist either.

**Comment by IDKwhattoputhere** [comment]
Thanks for the report.
uBO reformats the filter and it correctly reads: `/popup.$document,domain=~webopedia.com`
Since this filter is not needed for the site it targeted anymore and has caused problems before I removed it: https://github.com/IDKwhattoputhere/uBlock-Filters-Plus/commit/341630f261f78671e5641e0fd502a484cbdc12ae
It seems a little broad anyways.
