### ISSUE TITLE
Analysis pages for popads.net on external sites blocked

### ISSUE THREAD

**Issue by anonsubmitter** [IDKwhattoputhere/uBlock-Filters-Plus#8]
I'm not sure anything could be done about this since it's not going to affect that many sites and doing exclusions might not be possible without either risking that malicious popads domains slip through or manually whitelisting a large amount of pages that will not recieve much traffic, but I thought I'd bring it up for discussion anyway. Analysis pages for popads.net on external sites are blocked by the `/popads.$domain=~github.com|~githubusercontent.com,document` filter rule.

Examples:
`https://publicwww.com/websites/popads.net+popunder+code/`
`https://www.mywot.com/en/scorecard/popads.net`
`https://whois.domaintools.com/popads.net`
`https://who.is/whois/popads.net`
`https://builtwith.com/popads.net`
`https://w3techs.com/sites/info/popads.net`
`https://w3bin.com/domain/popads.net`
`https://www.similarweb.com/website/popads.net`
`http://www.alexa.com/siteinfo/popads.net`

**Comment by IDKwhattoputhere** [comment]
Removing the rule seems unnecessary for now since it takes one click if a site is negatively affected and this should rarely be a problem, like you said. But I made a fix anyways (https://github.com/IDKwhattoputhere/uBlock-Filters-Plus/commit/c032b35aad9b30e80b7967060e903fb3b0077d70). I don't have much of a problem disabling the rule on sites that don't use Popads or serve Popads' ads. Feel free to comment if I'm missing anything though.
